### ISSUE TITLE
dependency on bash.

### ISSUE THREAD

**Issue by ghost** [Financial-Times/service-status-go#2]
For our container builds, we use alpine Linux as the base and it doesn't have bash by default.  I wonder whether we really need bash as a dependency?

**Comment by dgem** [comment]
I'm not sure if it is a bash dependency beyond the #!/bin/bash comment... are you saying the ldFlags.sh doesn't work on Alpine ?

**Comment by izzyblues** [comment]
Fixed the script to work with SH
